// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXn8VXInsScbdXzgUIR4esXgt2i_On30',
    appId: '1:125546820655:web:58f0fe619e2f33ba0242da',
    messagingSenderId: '125546820655',
    projectId: 'ocr-microservices-8b792',
    authDomain: 'ocr-microservices-8b792.firebaseapp.com',
    storageBucket: 'ocr-microservices-8b792.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh6uFPEh6aLxzda10Uoog8ed4jB8MUhPg',
    appId: '1:125546820655:android:a846aeadca97b0170242da',
    messagingSenderId: '125546820655',
    projectId: 'ocr-microservices-8b792',
    storageBucket: 'ocr-microservices-8b792.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwjsx9QIDXJlieQeQaM80u6eoX03GFkM4',
    appId: '1:125546820655:ios:7eb1e4858a600d570242da',
    messagingSenderId: '125546820655',
    projectId: 'ocr-microservices-8b792',
    storageBucket: 'ocr-microservices-8b792.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwjsx9QIDXJlieQeQaM80u6eoX03GFkM4',
    appId: '1:125546820655:ios:7eb1e4858a600d570242da',
    messagingSenderId: '125546820655',
    projectId: 'ocr-microservices-8b792',
    storageBucket: 'ocr-microservices-8b792.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEXn8VXInsScbdXzgUIR4esXgt2i_On30',
    appId: '1:125546820655:web:ce253369c8cb125f0242da',
    messagingSenderId: '125546820655',
    projectId: 'ocr-microservices-8b792',
    authDomain: 'ocr-microservices-8b792.firebaseapp.com',
    storageBucket: 'ocr-microservices-8b792.firebasestorage.app',
  );

}